# Generated by Django 4.2.15 on 2024-09-01 04:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
        ('shipping', '0007_rename_default_address_is_default_address_is_primary'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('billing_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_method', models.CharField(blank=True, choices=[('Credit/ Debit/ ATM card', 'Credit/ Debit/ ATM card'), ('UPI', 'UPI'), ('Cash On Delivery', 'Cash On Delivery')], max_length=254, null=True)),
                ('payment_status', models.CharField(blank=True, choices=[('Payment Not Received', 'Payment Not Received'), ('Payment Received', 'Payment Received')], default='Payment Not Initiated', max_length=254, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('billing_address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shipping.address')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='orders.order')),
            ],
            options={
                'verbose_name': 'Payment',
                'verbose_name_plural': 'Payments',
            },
        ),
    ]
