# Generated by Django 4.2.15 on 2024-09-08 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_status',
            field=models.CharField(blank=True, choices=[('Payment Not Initiated', 'Payment Not Initiated'), ('Payment Not Received', 'Payment Not Received'), ('Payment Received', 'Payment Received')], default='Payment Not Initiated', max_length=254, null=True),
        ),
    ]
