# Generated by Django 4.2.15 on 2024-09-13 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_alter_payment_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='billing_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
