# Generated by Django 4.2.15 on 2024-09-14 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_alter_payment_billing_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='razorpay_payment_id',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_status',
            field=models.CharField(blank=True, choices=[('Payment Initiated', 'Payment Initiated'), ('Payment Not Received', 'Payment Not Received'), ('Payment Received', 'Payment Received')], default='Payment Not Initiated', max_length=254, null=True),
        ),
    ]
