# Generated by Django 4.2.15 on 2024-09-14 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_payment_razorpay_payment_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('card', 'Credit/ Debit/ ATM card'), ('netbanking', 'Net Banking'), ('upi', 'UPI'), ('wallet', 'Wallet'), ('Cash On Delivery', 'Cash On Delivery')], max_length=254, null=True),
        ),
    ]
