# Generated by Django 4.2.15 on 2024-08-12 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_customerprofile_gender_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerprofile',
            name='country_code',
            field=models.CharField(blank=True, default='+91', max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
