# Generated by Django 4.2.15 on 2024-08-28 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_customerprofile_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerprofile',
            name='old_cart',
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='previous_cart',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
