# Generated by Django 4.2.15 on 2024-08-12 04:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=254, null=True)),
                ('last_name', models.CharField(blank=True, max_length=254, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('country_code', models.CharField(blank=True, default='+91', max_length=5, null=True)),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('address_line1', models.TextField(blank=True, max_length=254, null=True)),
                ('address_line2', models.TextField(blank=True, max_length=254, null=True)),
                ('landmark', models.TextField(blank=True, max_length=254, null=True)),
                ('zip_code', models.CharField(blank=True, max_length=10, null=True)),
                ('state', models.TextField(blank=True, max_length=254, null=True)),
                ('country', models.TextField(blank=True, max_length=254, null=True)),
                ('last_updated', models.DateField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Address',
                'verbose_name_plural': 'Addresses',
            },
        ),
    ]
