# Generated by Django 4.2.15 on 2024-08-12 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipping', '0002_address_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='city',
            field=models.TextField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='default',
            field=models.BooleanField(default=False),
        ),
    ]
