# Generated by Django 4.2.15 on 2024-08-17 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipping', '0005_alter_address_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='last_updated',
        ),
        migrations.AddField(
            model_name='address',
            name='date_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
