# Generated by Django 4.2.15 on 2024-09-08 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_order_date_delivered'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='date_cancelled',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(blank=True, choices=[('In Cart', 'In Cart'), ('Order Received', 'Order Received'), ('Order Confirmed', 'Order Confirmed'), ('Order Rejected', 'Order Rejected'), ('Order Cancelled', 'Order Cancelled'), ('Order Shipped', 'Order Shipped'), ('Order Delivered', 'Order Delivered')], default='In Cart', max_length=254, null=True),
        ),
    ]
