# Generated by Django 4.2.15 on 2024-09-14 04:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_order_order_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='order_id',
            new_name='razorpay_order_id',
        ),
    ]
