# Generated by Django 4.2.15 on 2024-08-17 05:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('name', models.CharField(max_length=254)),
                ('slug', models.CharField(blank=True, max_length=254, primary_key=True, serialize=False, unique=True)),
                ('description', models.CharField(blank=True, max_length=500, unique=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('parent_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='products.category')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
                ('price', models.FloatField()),
                ('stock', models.IntegerField()),
                ('is_featured', models.BooleanField(default=False)),
                ('is_sale', models.BooleanField(default=False)),
                ('sale_price', models.FloatField(blank=True, null=True)),
                ('description', models.CharField(blank=True, max_length=1000, unique=True)),
                ('image', models.ImageField(upload_to='products/')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category', to='products.category')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
            },
        ),
    ]
