# Generated by Django 4.2.15 on 2024-08-17 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_alter_product_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='data_sheet',
            new_name='specification',
        ),
    ]
