# Generated by Django 4.2.15 on 2024-08-19 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_rename_data_sheet_product_specification'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(default='categories/default_category.jpg', upload_to='categories/'),
        ),
    ]
