# Generated by Django 4.2.15 on 2024-08-27 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_product_max_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='delivery_charge',
            field=models.FloatField(default=40),
        ),
    ]
