# Generated by Django 4.2.15 on 2024-09-11 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.CharField(choices=[('1', 'Bad'), ('2', 'Below Average'), ('3', 'Average'), ('4', 'Good'), ('5', 'Excellent')], max_length=30),
        ),
    ]
