# Generated by Django 4.2.15 on 2024-09-11 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_alter_review_rating'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Review',
        ),
    ]
